# Episode 0 — JAX Is NumPy

**Instructor notebook** · run top-to-bottom before recording.

Hello JAX. `jax.numpy` (`jnp`) works like NumPy — create arrays, read shapes, name them.

| | |
|---|---|
| **Prereq** | Python |
| **Next** | Episode 1 — PRNG keys, `params`, and broadcasting |

**JAX docs:** [JAX 101](https://jax.readthedocs.io/en/latest/jax-101.html) · [`jax.numpy`](https://jax.readthedocs.io/en/latest/jax.numpy.html)

In [1]:
import jax
import jax.numpy as jnp

## Arrays and shapes

Same as NumPy: `jnp.array`, `jnp.arange`, `.shape`, `.dtype`.

In [2]:
x = jnp.array([1.0, 2.0, 3.0, 4.0])
m = jnp.arange(12).reshape(3, 4)

print("x:", x.shape, x.dtype)
print("m:", m.shape)
print(m)

x: (4,) float32
m: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Shapes

| Array | Shape |
|-------|-------|
| `x` | `(N,)` — vector of length `N` |
| `m` | `(I, J)` — matrix |

## Indexing

Identical to NumPy.

In [3]:
print("row 0:", m[0])
print("cell [1,2]:", m[1, 2])

row 0: [0 1 2 3]
cell [1,2]: 6


## Immutability

Unlike NumPy, you cannot write `x[0] = 99` — JAX raises `TypeError: JAX arrays are immutable`.

Updates return a **new** array via `.at[...].set(...)`. The original is untouched. (This matters once we `jit` and differentiate.)

In [4]:
try:
    x[0] = 99.0
except TypeError as e:
    print(type(e).__name__, ":", e)

x_new = x.at[0].set(99.0)
print("x:    ", x)
print("x_new:", x_new)

TypeError : JAX arrays are immutable and do not support in-place item assignment. Instead of x[idx] = y, use x = x.at[idx].set(y) or another .at[] method: https://docs.jax.dev/en/latest/_autosummary/jax.numpy.ndarray.at.html
x:     [1. 2. 3. 4.]
x_new: [99.  2.  3.  4.]


---
## Exercise

1. Make `y = jnp.arange(5)` and print `y.shape`
2. Print `y[3]`

*(Solution below.)*

In [5]:
y = jnp.arange(5)
print(y.shape)
print(y[3])

(5,)
3


**Next:** Episode 1 — PRNG keys, `params`, and broadcasting.